### ISSUE TITLE
Unable to lookup DID with selfhosted PDS server

### ISSUE THREAD

**Issue by uriel1998** [sugyan/tuisky#31]
I have successfully set up a [selfhosted PDS server](https://docs.bsky.app/blog/self-host-federation) for Bluesky, but I'm unable to log in with tuisky.  I *suspect* this is because 

https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=stevensaus.com

fails, although if it is called to my PDS server itself:

https://example.com/xrpc/com.atproto.identity.resolveHandle?handle=stevensaus.com

I get the expected JSON response with my DID.  However, I don't know rust for anything, so this is a guess. Does this make sense given the logic of the program, and if so, is there a way that a knowledgeable end user (who is completely ignorant of rust outside of typing `cargo install`) is able to specify the PDS to use?

**Comment by sugyan** [comment]
Thanks for the report!
Yes, it is true that accounts with selfhosted PDS cannot be logged in with the current `tuisky`. You have to specify the PDS endpoint at login (e.g. `https://sky.faithcollapsing.com/` instead of `https://bsky.social` ) to be able to log in with the selfhosted PDS account.

I was going to support this later, but forgot...
Added `service` input to the login form in #32. The default value uses `https://bsky.social`, but I think you can specify your PDS host here and it will allow you to log in.

**Comment by sugyan** [comment]
I've published `0.1.3`, please try it out!
https://crates.io/crates/tuisky/0.1.3

**Comment by uriel1998** [comment]
Great success!  Works with both DID and email address (not handle, in case someone else stumbles upon this later).  Thank you so much for your quick response!
